version: '3.4'

services:

  inventory-db:
    image: 'postgres:13.1-alpine'
    container_name: inventory-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=inventory-user
      - POSTGRES_PASSWORD=inventory-password
      - POSTGRES_DB=inventory-db

  inventory-service:
    container_name: inventory-service
    depends_on:
      - inventory-db
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATASOURCE_URL=jdbc:postgresql://inventory-db:5432/inventory-db
      - DATASOURCE_USERNAME=inventory-user
      - DATASOURCE_PASSWORD=inventory-password