version: '3.4'

services:

  configuration-db:
    image: 'postgres:13.1-alpine'
    container_name: configuration-db
    environment:
      - POSTGRES_USER=configuration-user
      - POSTGRES_PASSWORD=configuration-password
      - POSTGRES_DB=configuration-db
    networks:
      - configuration

  configuration-service:
    container_name: configuration-service
    depends_on:
      - configuration-db
    build:
      context: ./configuration-service
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      - DATASOURCE_URL=jdbc:postgresql://configuration-db:5432/configuration-db
      - DATASOURCE_USERNAME=configuration-user
      - DATASOURCE_PASSWORD=configuration-password
    networks:
      - ecommerce
      - configuration

  inventory-db:
    image: 'postgres:13.1-alpine'
    container_name: inventory-db
    environment:
      - POSTGRES_USER=inventory-user
      - POSTGRES_PASSWORD=inventory-password
      - POSTGRES_DB=inventory-db
    networks:
      - inventory

  inventory-service:
    container_name: inventory-service
    depends_on:
      - configuration-service
      - inventory-db
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - ecommerce
      - inventory

networks:
  ecommerce:
  configuration:
  inventory: