CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID          BIGINT        NOT NULL PRIMARY KEY,
    NAME        VARCHAR(255)  NOT NULL,
    BRAND_ID    BIGINT        NOT NULL,
    CATEGORY_ID BIGINT        NOT NULL,
    UNIT_PRICE  NUMERIC(6, 2) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS PRODUCT_SEQ;

CREATE TABLE CATEGORY
(
    ID   BIGINT       NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS CATEGORY_SEQ;

CREATE TABLE IF NOT EXISTS BRAND
(
    ID   BIGINT       NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS BRAND_SEQ;