CREATE TABLE PROPERTIES
(
    ID          INT PRIMARY KEY,
    APPLICATION VARCHAR(255),
    PROFILE     VARCHAR(255),
    LABEL       VARCHAR(255),
    KEY         VARCHAR(255),
    VALUE       VARCHAR(255)
);